config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  resources :users, only: [:show]
  resources :categories, :authors, :publishers, only: %i(index show)
  resources :books, only: [:show, :index] do
    resources :comments, only: %i(create update destroy)
    resources :likes, :follows, only: %i(create destroy)
    resources :borrows, except: %i(index destroy)
  end

  namespace :admin do
    root "borrows#index"
    resources :users, :authors, :categories, :publishers, :borrows
    resources :books do
      resources :comments, only: %i(create update destroy)
      resources :likes, :follows, only: %i(create destroy)
      resources :borrows
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags
  has_many :likes, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :borrows
  belongs_to :category
  belongs_to :author
  belongs_to :publisher
  
  mount_uploader :picture, PictureUploader
  validates :title, :status, presence: true

  scope :select_books, (lambda do
    includes(:likes, :borrows, :follows)
    .select("books.*, authors.name AS author_name")
    .joins(:author)
  end)
  scope :created_at_desc, -> {order created_at: :desc}

  scope :search, (lambda do |search|
    select_books
    .where "books.title LIKE ? OR authors.name LIKE ?", "%#{search}%", "%#{search}%"
  end)
  scope :get_by_category, -> ctg_id {where category_id: ctg_id}
  scope :get_by_publisher, -> pub_id {where publisher_id: pub_id}

  scope :suggest_books, (lambda do |book|
    select_books.where("category_id = ? AND books.id != ?", book.category_id, book.id).sample(3)
  end)

  scope :new_books, -> {select_books.created_at_desc.limit 6}
  
  scope :outstanding_books, (lambda do
    includes(:borrows, :follows)
    .select("books.*, authors.name AS author_name")
    .joins(:author, :likes)
    .where("likes.created_at BETWEEN (CURRENT_DATE - 30) AND (CURRENT_DATE + 1)")
    .group("books.id, author_name").order("COUNT(*) desc").limit 4
  end)

  scope :most_borrow_books, (lambda do
    includes(:likes, :follows)
    .select("books.*, authors.name AS author_name")
    .joins(:author, :borrows)
    .where("borrows.created_at BETWEEN (CURRENT_DATE - 30) AND (CURRENT_DATE + 1)")
    .group("books.id, author_name").order("COUNT(*) desc").limit 6
  end)

  def atr_name=(name)
    @atr_name = name
    self.author = Author.find_or_initialize_by(name: name)
  end

  def atr_name
    @atr_name
  end

  def pub_name=(name)
    @pub_name = name
    self.publisher = Publisher.find_or_initialize_by(name: name)
  end

  def pub_name
    @pub_name
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < AdminController
  before_action :get_book, except: %i(index new create)

  def index
    @books = Book.search(params[:search]).created_at_desc
    @books = @books.get_by_category params[:ctg_id] if params[:ctg_id].present?
    @books = @books.get_by_publisher params[:pub_id] if params[:pub_id].present?
    
    @books = @books.page(params[:page]).per Settings.pages.per_book
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @book = Book.new
    respond_to {|format| format.js}
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t ".create_success"
      redirect_to admin_books_path
    else
      flash[:error] = t ".create_fail"
      redirect_to admin_books_path
    end
  end

  def show
    @comments = @book.comments.created_at_desc
  end

  def edit
    respond_to {|format| format.js}
  end

  def update
    if @book.update_attributes book_params
      flash[:success] = t ".update_success"
    else
      flash[:error] = t ".update_fail"
    end
    redirect_to admin_book_path(@book)
  end

  def destroy
    if @book.status
      if @book.destroy
        flash[:success] = t ".delete_success"
        redirect_to admin_books_url
      else
        flash[:danger] = t ".delete_fail"
        redirect_to admin_book_path(@book)
      end
    else
      flash[:danger] = t ".not_delete"
      redirect_to admin_book_path(@book)
    end
  end

  private

  def book_params
    params.require(:book).permit :title, :describe, :published_at,
      :category_id, :atr_name, :pub_name, :picture
  end

  def get_book
    @book = Book.find_by id: params[:id]
    return if @book
      flash[:warning] = t ".not_found"
      redirect_to admin_books_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.search(params[:search]).created_at_desc
    @books = @books.get_by_category params[:ctg_id] if params[:ctg_id].present?
    @books = @books.get_by_publisher params[:pub_id] if params[:pub_id].present?
    
    @books = @books.page(params[:page]).per Settings.pages.per_book
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @book = Book.find_by id: params[:id]
    @comments = @book.comments.created_at_desc
    @sg_books = Book.suggest_books @book
  end
end

app/views/admin/books/_edit.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title"><%= t ".edit_book"%></h4>
      <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
    <div class="modal-body">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book] do |f| %>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :title, t(".book_title"), class: "col-md-3" %>
      <%= f.text_field :title, class: "form-control", placeholder: "Rừng Na Uy" %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :describe, t(".describe"), class: "col-md-3" %>
      <%= f.text_area :describe, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :category, t(".category"), class: "col-md-3" %>
      <%= f.collection_select :category_id, Category.all, :id, :title, {}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :author, t(".author"), class: "col-md-3" %>
      <%#= f.collection_select :author_id, Author.all, :id, :name, {}, class: "form-control" %>
      <%= f.text_field :atr_name, class: "form-control", placeholder: "Jack London" %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :publisher, t(".publisher"), class: "col-md-3" %>
      <%#= f.collection_select :publisher_id, Publisher.all, :id, :name, {}, class: "form-control" %>
      <%= f.text_field :pub_name, class: "form-control", placeholder: "NXB ADBC" %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :published_at, t(".published_at"), class: "col-md-3" %>
      <%= f.date_field :published_at, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :picture, t(".picture"), class: "col-md-3" %>
      <span class="picture"><%= f.file_field :picture %></span>
    </div>
  </div>
  <%= f.submit t(".submit"), class: "btn" %>
<% end %>

app/views/admin/books/_new.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title"><%= t ".new_book"%></h4>
      <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
    <div class="modal-body">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/books/_table.html.erb
<% if books.any? %>
  <% serial_number params[:page].to_i, Settings.pages.per_book %>
  <% books.each.with_index do |book, i| %>
    <tr class="text-center">
      <td><%= @idx + i+1 %></td>
      <td class="text-justify"><%= link_to book.title, admin_book_path(book),
        class: "text-dark" %></td>
      <td><%= link_to book.author_name, admin_author_path(book.author_id),
        class: "text-dark" %></td>
      <td><%= book.published_at %></td>
      <td>
      <% if book.picture? %>
        <%= link_to image_tag(book.picture.url, alt: "Book image", class: "book-img"),
          admin_book_path(book) %>
      <% else %>
      <%= link_to image_tag("https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/18782.jpg",
        class: "book-img"), admin_book_path(book) %>
      <% end %>
      </td>
      <td><div class="b_describe text-justify"><%= book.describe %></div></td>
      <td>
        <%= link_to content_tag(:i, t(".edit"), class: "fa fa-edit"),
          edit_admin_book_path(book), remote: true, class: "text-dark" %>
        <% if book.status %>
          <%= link_to content_tag(:i, t(".delete"), class: "fa fa-trash-o"),
            admin_book_path(book), method: :delete, class: "text-danger",
            data: {confirm: t("delete_confirm")} %>
        <% end %>
      </td>
    </tr>
  <% end %>
<% else %>
  <tr class="d-flex">
    <td><%= t "admin.categories.table.no_result" %></td>
  </tr>
<% end %>

app/views/admin/books/edit.js.erb
$("#myModal").html("<%= escape_javascript(render "edit") %>");
$("#myModal").modal();

app/views/admin/books/index.html.erb
<% provide(:title, t(".manage_book")) %>
<nav aria-label="breadcrumb" class="col-md-12">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t("home"), admin_root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t(".books")%></li>
  </ol>
</nav>
<div class="row col-md-12">
  <div class="col-md-5">
    <h5 id="result">
      <%= "#{t(".list_have")} #{@books.total_count} #{t(".books")}" %>
    </h5>
  </div>
  <div class="col-md-4"></div>
  <%= link_to content_tag(:i, t(".filter"), class: "fa fa-filter"), "",
    class: "btn filter-show" %>
  <%= link_to content_tag(:i, t(".create_book"), class: "fa fa-book"),
    new_admin_book_path, remote: true, data: {toggle: "modal", target: "#myModal"},
    class: "btn" %>
  <div class="col-md-12 filter hidden">
    <%= form_tag url_for, method: :get, remote: true do %>
      <div class="form-group">
        <div class="input-group">
          <div class="col-md-5">
          <%= label_tag :search, t(".book_or_author") %>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          </div>
          <div class="col-md-3">
          <%= label_tag :ctg_title, t("admin.books.form.category") %>
          <%= select_tag :ctg_title,
              options_from_collection_for_select(Category.all, :title, :title),
              prompt: "Select category", class: "form-control" %>
          </div>
          <div class="col-md-3">
          <%= label_tag :pub_name, t("admin.books.form.publisher") %>
          <%= select_tag :pub_name,
              options_from_collection_for_select(Publisher.all, :name, :name),
              prompt: "Select publisher", class: "form-control" %>
          </div>
          <%= submit_tag "Search", name: nil, class: "btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="col-md-12 mt-3">
  <table class="table table-bordered table-hover bg-lightblue">
    <thead>
      <tr class="text-center">
        <th><%= t(".stt") %></th>
        <th><%= t(".title") %></th>
        <th><%= t(".author") %></th>
        <th><%= t(".published_at") %></th>
        <th><%= t(".picture") %></th>
        <th><%= t(".describe") %></th>
        <th></th>
      </tr>
    </thead>
    <tbody id="data-table" class="bg-white">
      <%= render partial: "table", locals: {books: @books} %>
    </tbody>
  </table>
  <div id="pagination">
  <%= paginate @books, remote: true, window: 2, theme: "twitter-bootstrap-4",
    pagination_class: "justify-content-center" %>
  </div>
</div>

app/views/admin/books/index.js.erb
$("#result").html("<%= escape_javascript("#{t(".list_have")} #{@books.total_count} #{t(".books")}")%>")
$("#data-table").html("<%= escape_javascript(render partial: "table", locals: {books: @books}) %>")

$("#pagination").html("<%= escape_javascript(paginate @books, remote: true,
  window: 2, theme: "twitter-bootstrap-4",
  pagination_class: "justify-content-center") %>")

$("html, body").animate({ scrollTop: 0 }, "fast")

app/views/admin/books/show.html.erb
<% provide(:title, @book.title) %>
<nav aria-label="breadcrumb" class="col-md-12">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t("home"), admin_root_path %></li>
    <li class="breadcrumb-item"><%= link_to t(".books"), admin_books_path %></li></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @book.title %></li>
  </ol>
</nav>
<div class="row col-md-12 border bg-white">
  <%= render partial: "books/show" %>
</div>