config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  resources :users, only: [:show]
  resources :categories, :authors, :publishers, only: %i(index show)
  resources :books, only: [:show, :index] do
    resources :comments, only: %i(create update destroy)
    resources :likes, :follows, only: %i(create destroy)
    resources :borrows, except: %i(index destroy)
  end

  namespace :admin do
    root "borrows#index"
    resources :users, :authors, :categories, :publishers, :borrows
    resources :books do
      resources :comments, only: %i(create update destroy)
      resources :likes, :follows, only: %i(create destroy)
      resources :borrows
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent, class_name: "Category"
  has_many :books
  has_many :children, class_name: "Category", foreign_key: :parent_id

  validates :title, presence: true, uniqueness: true, length: {maximum: 30}

  scope :select_categories, ->{includes(:books).select :id, :title, :describe}
  scope :get_by_title, -> title {where("title LIKE ?", "%#{title}%")}
  scope :get_parent, -> {includes(:children).where parent_id: nil}

  def is_parent?
    !!self.parent.nil?
  end

  def has_parent?
    !!self.parent.present?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :get_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.select_categories.get_by_title(params[:search])
                          .order(:title).includes(:books)
                          .page(params[:page]).per Settings.pages.per_ctg
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "#{t(".add_success")} #{@category.title}"
      redirect_to admin_categories_path
    else
      flash[:error] = t ".add_fail"
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".update_success"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    unless @category.books.any?
      if @category.destroy
        flash[:success] = t ".delete_success"
      else
        flash[:danger] = t ".delete_fail"
      end
    else
      flash[:danger] = t ".ctg_has_books"
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title, :describe, :parent_id)
  end

  def get_category
    @category = Category.find_by id: params[:id]
    return if @category
      flash[:danger] = t "not_found" + params[:id]
      redirect_to admin_categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.get_parent.select_categories
  end

  def show
    @category = Category.find_by id: params[:id]
    @books = @category.books.select_books
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :title, t("admin.categories.index.title"), class: "col-md-4" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :describe, t("admin.categories.index.describe"), class: "col-md-4" %>
      <%= f.text_area :describe, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :parent, t("admin.categories.index.parent"), class: "col-md-4" %>
      <%= f.collection_select :parent_id, Category.all, :id, :title, prompt: true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit t(".create"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/categories/_table.html.erb
<% if categories.any? %>
  <% serial_number params[:page].to_i, Settings.pages.per_ctg %>
  <% categories.each.with_index do |ctg, i| %>
    <tr class="d-flex">
      <td class="col-1 text-center"><%= @idx + i+1 %></td>
      <td class="col-3"><%= ctg.title %></td>
      <td class="col-1 text-center"><%= ctg.books.length %></td>
      <td class="col-6"><%= ctg.describe %></td>
      <td class="col-1">
        <%= link_to t(".edit"), edit_admin_category_path(ctg) %>
        <% unless ctg.books.any? %>
          <%= link_to t(".delete"), admin_category_path(ctg), method: :delete,
            data: {confirm: t("delete_confirm")} %>
        <% end %>
      </td>
    </tr> 
  <% end %>
<% else %>
  <tr class="d-flex">
    <td class="col-12 text-center"><%= t ".no_result" %></td>
  </tr>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide(:title, t(".edit_ctg")) %>
<div class="col-md-8 border border-primary rounded my-md-5">
  <div class="col-md-12">
    <h2 class="text-center my-md-3"><%= t(".edit_ctg") %></h2>
  </div>
  <%= render "form" %>
</div>

app/views/admin/categories/index.html.erb
<% provide(:title, t(".manage_category")) %>
<nav aria-label="breadcrumb" class="col-md-12">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t("home"), admin_root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t ".categories" %></li>
  </ol>
</nav>
<h5 class="col-md-12"><%= t ".list_ctg" %></h5>
<div class="col-md-5">
  <%= form_tag url_for, method: :get, remote: true do %>
    <div class="form-group">
      <div class="input-group">
        <%= text_field_tag :search, params[:search], class: "form-control" %>
        <%= submit_tag "Search", name: nil, class: "btn-primary" %>
      </div>
    </div>
  <% end %>
</div>
<div class="col-md-5"></div>
<div class="col-md-2">
  <%= link_to t(".create_category"), new_admin_category_path, class: "btn" %>
</div>
<h5 id="result" class="col-md-12">
  <%= t(".have") +"#{@categories.total_count}"+ t(".result") %>
</h5>
<div class="col-md-12">
  <table class="table table-bordered table-hover bg-primary">
    <thead>
      <tr class="text-center">
        <th><%= t(".stt") %></th>
        <th><%= t(".title") %></th>
        <th><%= t(".books") %></th>
        <th><%= t(".describe") %></th>
        <th></th>
      </tr>
    </thead>
    <tbody class="bg-white" id="data-table">
      <%= render partial: "table", locals: {categories: @categories} %>
    </tbody>
  </table>
  <div id="pagination">
    <%= paginate @categories, remote: true, window: 2, theme: "twitter-bootstrap-4",
      pagination_class: "justify-content-center", id: "pagination" %>
  </div>
</div>

app/views/admin/categories/index.js.erb
$("#result").html("<%= escape_javascript(t(".have") +"#{@categories.total_count}"+ t(".result"))%>")
$("#data-table").html("<%= escape_javascript(render partial: "table",
  locals: {categories: @categories}) %>")
$("#pagination").html("<%= escape_javascript(paginate @categories, remote: true,
  window: 2, theme: "twitter-bootstrap-4",
  pagination_class: "justify-content-center") %>")

app/views/admin/categories/new.html.erb
<% provide(:title, t(".create_ctg")) %>
<div class="col-md-8 border border-primary rounded my-md-5">
  <div class="col-md-12">
    <h2 class="text-center my-md-3"><%= t(".create_ctg") %></h2>
  </div>
  <%= render "form" %>
</div>