config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  resources :users, only: [:show]
  resources :categories, :authors, :publishers, only: %i(index show)
  resources :books, only: [:show, :index] do
    resources :comments, only: %i(create update destroy)
    resources :likes, :follows, only: %i(create destroy)
    resources :borrows, except: %i(index destroy)
  end

  namespace :admin do
    root "borrows#index"
    resources :users, :authors, :categories, :publishers, :borrows
    resources :books do
      resources :comments, only: %i(create update destroy)
      resources :likes, :follows, only: %i(create destroy)
      resources :borrows
    end
  end
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  enum status: %i{waitting active refuse cancelled returned lated}

  validates :date_borrow, :borrow_days, presence: true

  scope :get_borrow, (lambda do |bor_id|
    select("borrows.*, users.id AS user_id, users.name AS user_name,
      books.id AS book_id, books.title AS book_title, books.status AS book_status")
    .joins(:user, :book).find_by id: bor_id
  end)
  scope :search_borrows, (lambda do |params|
    select("borrows.*, users.id AS user_id, users.name AS user_name,
      books.id AS book_id, books.title AS book_title, books.status AS book_status")
    .joins(:user, :book)
    .where("users.name LIKE ? AND books.title LIKE ?",
      "%#{params[:user_name]}%", "%#{params[:book_title]}%")
    .order(created_at: :desc)
  end)
  scope :get_by_status, -> status {where status: status}
  scope :get_by_date_borrow, (lambda do |params|
    where "date_borrow BETWEEN ? AND ?", params[:from_date], params[:to_date]
  end)
  scope :count_borrows, (lambda do
    where "EXTRACT(YEAR_MONTH FROM date_borrow) = EXTRACT(YEAR_MONTH FROM CURDATE()) - 1"
  end)
  scope :count_accepts, (lambda do
    where "(EXTRACT(YEAR_MONTH FROM date_borrow) = EXTRACT(YEAR_MONTH FROM CURDATE()) - 1) AND status IN (1, 4)"
  end)
  scope :count_returns, (lambda do
    where "EXTRACT(YEAR_MONTH FROM date_return) = EXTRACT(YEAR_MONTH FROM CURDATE()) - 1"
  end)
end

app/controllers/admin/borrows_controller.rb
class Admin::BorrowsController < AdminController
  
  def index
    @data = Borrow.group(:status).group_by_day(:created_at).count
    @borrows = Borrow.search_borrows params
    if params[:from_date].present? && params[:to_date].present?
      @borrows = @borrows.get_by_date_borrow params
    end
    @borrows = @borrows.get_by_status params[:status] if params[:status].present?
    @borrows = @borrows.page(params[:page]).per Settings.pages.per_ctg
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @borrow = Borrow.get_borrow params[:id]
    if @borrow.waitting?
      if @borrow.book_status && params[:status] == "active"
        update_borrow_book @borrow
      elsif params[:status] == "refuse"
        update_borrow @borrow
      end
    elsif @borrow.active? || @borrow.lated?
      if !@borrow.book_status && params[:status] == "returned"
        @borrow.update_attributes date_return: Date.today
        update_borrow_book @borrow
      end
    end
    respond_to do |format|
      format.html {redirect_to admin_borrows_path}
      format.js
    end
  end

  private

  def update_borrow borrow
    if borrow.update_attributes status: params[:status]
      BorrowMailer.update_borrow_email(borrow.user, borrow).deliver_later
    end
  end

  def update_borrow_book borrow
    update_borrow borrow
    borrow.book.toggle! :status
  end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :get_book

  def new
    @borrow = Borrow.new
    respond_to {|format| format.js}
  end

  def create
    if @book.status
      @borrow = @book.borrows.build borrow_params
      @borrow.user = current_user
      if @borrow.save
        flash[:success] = "#{t(".borrow_success")} #{@book.title}"
      else
        flash[:error] = t(".borrow_fail")
      end
    else
      flash[:danger] = "#{@book.title} #{t(".is_borrowed")}"
    end
    redirect_to @book
  end

  def update
    @borrow = Borrow.find_by id: params[:id]
    @borrow.update_attributes status: params[:status]
    respond_to {|format| format.js}
  end

  private

  def borrow_params
    params.require(:borrow).permit(:date_borrow, :borrow_days)
  end

  def get_book
    @book = Book.find_by id: params[:book_id]
  end
end

app/views/borrows/_borrow.html.erb
<td><%= link_to borrow.book.title, book_path(borrow.book_id),
  class: "text-dark" %></td>
<td><%= borrow.date_borrow %></td>
<td><%= borrow.borrow_days %></td>
<td><%= borrow.status %></td>
<td><%= borrow.date_return %></td>
<td>
  <% if borrow.waitting? && @user == current_user %>
    <%= link_to t(".cancel"), book_borrow_path(borrow.book_id, borrow, params.permit().merge(status: :cancelled)),
      remote: true, method: :put, class: "" %>
  <% end %>
</td>

app/views/borrows/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <% if @book.picture? %>
      <%= image_tag @book.picture.url, alt: "Card image cap", class: "card-img-top" %>
    <% else %>
      <%= image_tag "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/4600.jpg?v=2&w=340&h=497",
    alt: "Card image cap", class: "card-img-top" %>
    <% end %>
  </div>
  <div class="col-md-8">
    <%= form_for @borrow, url: book_borrows_path do |f| %>
      <div class="form-group">
        <h5 class="input-group"><%= @book.title %> - <%= @book.author.name %></h5>
      </div>
      <div class="form-group">
        <div class="input-group">
          <%= f.label :date_borrow, class: "col-md-5" %>
          <%= f.date_field :date_borrow, min: Date.today + 1, id: "date-borrow",
            class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="input-group">
          <%= f.label :borrow_days, class: "col-md-5" %>
          <%= f.number_field :borrow_days, min: 1, max: 90, id: "num-days", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="input-group">
          <%= f.label :date_return, class: "col-md-5" %>
          <div id="date_return"></div>
        </div>
      </div>
      <br>
      <%= f.submit "Submit", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/borrows/_new.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title"><%= t ".borrow_book"%></h4>
      <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
    <div class="modal-body">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/borrows/_table.html.erb
<% @borrows.each do |borrow| %>
  <tr id="borrow-<%= borrow.id %>" class="text-center">
    <%= render borrow %>
  </tr>
<% end %>

app/views/borrows/new.js.erb
$("#myModal").html("<%= escape_javascript(render "new") %>");
$("#myModal").modal();

app/views/borrows/update.js.erb
$("#borrow-<%= @borrow.id %>").html("<%=  escape_javascript(render @borrow)%>");