config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  resources :users, only: [:show]
  resources :categories, :authors, :publishers, only: %i(index show)
  resources :books, only: [:show, :index] do
    resources :comments, only: %i(create update destroy)
    resources :likes, :follows, only: %i(create destroy)
    resources :borrows, except: %i(index destroy)
  end

  namespace :admin do
    root "borrows#index"
    resources :users, :authors, :categories, :publishers, :borrows
    resources :books do
      resources :comments, only: %i(create update destroy)
      resources :likes, :follows, only: %i(create destroy)
      resources :borrows
    end
  end
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  enum status: %i{waitting active refuse cancelled returned lated}

  validates :date_borrow, :borrow_days, presence: true

  scope :get_borrow, (lambda do |bor_id|
    select("borrows.*, users.id AS user_id, users.name AS user_name,
      books.id AS book_id, books.title AS book_title, books.status AS book_status")
    .joins(:user, :book).find_by id: bor_id
  end)
  scope :search_borrows, (lambda do |params|
    select("borrows.*, users.id AS user_id, users.name AS user_name,
      books.id AS book_id, books.title AS book_title, books.status AS book_status")
    .joins(:user, :book)
    .where("users.name LIKE ? AND books.title LIKE ?",
      "%#{params[:user_name]}%", "%#{params[:book_title]}%")
    .order(created_at: :desc)
  end)
  scope :get_by_status, -> status {where status: status}
  scope :get_by_date_borrow, (lambda do |params|
    where "date_borrow BETWEEN ? AND ?", params[:from_date], params[:to_date]
  end)
  scope :count_borrows, (lambda do
    where "EXTRACT(YEAR_MONTH FROM date_borrow) = EXTRACT(YEAR_MONTH FROM CURDATE()) - 1"
  end)
  scope :count_accepts, (lambda do
    where "(EXTRACT(YEAR_MONTH FROM date_borrow) = EXTRACT(YEAR_MONTH FROM CURDATE()) - 1) AND status IN (1, 4)"
  end)
  scope :count_returns, (lambda do
    where "EXTRACT(YEAR_MONTH FROM date_return) = EXTRACT(YEAR_MONTH FROM CURDATE()) - 1"
  end)
end

app/controllers/admin/borrows_controller.rb
class Admin::BorrowsController < AdminController
  
  def index
    @data = Borrow.group(:status).group_by_day(:created_at).count
    @borrows = Borrow.search_borrows params
    if params[:from_date].present? && params[:to_date].present?
      @borrows = @borrows.get_by_date_borrow params
    end
    @borrows = @borrows.get_by_status params[:status] if params[:status].present?
    @borrows = @borrows.page(params[:page]).per Settings.pages.per_ctg
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @borrow = Borrow.get_borrow params[:id]
    if @borrow.waitting?
      if @borrow.book_status && params[:status] == "active"
        update_borrow_book @borrow
      elsif params[:status] == "refuse"
        update_borrow @borrow
      end
    elsif @borrow.active? || @borrow.lated?
      if !@borrow.book_status && params[:status] == "returned"
        @borrow.update_attributes date_return: Date.today
        update_borrow_book @borrow
      end
    end
    respond_to do |format|
      format.html {redirect_to admin_borrows_path}
      format.js
    end
  end

  private

  def update_borrow borrow
    if borrow.update_attributes status: params[:status]
      BorrowMailer.update_borrow_email(borrow.user, borrow).deliver_later
    end
  end

  def update_borrow_book borrow
    update_borrow borrow
    borrow.book.toggle! :status
  end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :get_book

  def new
    @borrow = Borrow.new
    respond_to {|format| format.js}
  end

  def create
    if @book.status
      @borrow = @book.borrows.build borrow_params
      @borrow.user = current_user
      if @borrow.save
        flash[:success] = "#{t(".borrow_success")} #{@book.title}"
      else
        flash[:error] = t(".borrow_fail")
      end
    else
      flash[:danger] = "#{@book.title} #{t(".is_borrowed")}"
    end
    redirect_to @book
  end

  def update
    @borrow = Borrow.find_by id: params[:id]
    @borrow.update_attributes status: params[:status]
    respond_to {|format| format.js}
  end

  private

  def borrow_params
    params.require(:borrow).permit(:date_borrow, :borrow_days)
  end

  def get_book
    @book = Book.find_by id: params[:book_id]
  end
end

app/views/admin/borrows/_borrow.html.erb
<td><%= link_to borrow.user_name, admin_user_path(borrow.user_id),
  class: "text-dark" %></td>
<td><%= link_to borrow.book_title, admin_book_path(borrow.book_id),
  class: "text-dark" %></td>
<td><%= borrow.date_borrow %></td>
<td><%= borrow.borrow_days %></td>
<td><%= borrow.status %></td>
<td><%= borrow.date_return %></td>
<td>
  <% if borrow.waitting? %>
    <% if borrow.book_status %>
      <%= link_to t(".accept"), admin_borrow_path(borrow, params.permit().merge(status: :active)),
        remote: true, method: :put, class: "" %>
    <% end %>
    <%= link_to t(".refuse"), admin_borrow_path(borrow, params.permit().merge(status: :refuse)),
      remote: true, method: :put, class: "text-warning" %>
  <% elsif borrow.active? || borrow.lated? %>
    <%= link_to t(".return"), admin_borrow_path(borrow, params.permit().merge(status: :returned)),
      remote: true, method: :put, class: "text-success" %>
  <% end %>
</td>

app/views/admin/borrows/_table.html.erb
<% @borrows.each do |borrow| %>
  <tr id="borrow-<%= borrow.id %>" class="text-center">
    <%= render borrow %>
  </tr>
<% end %>

app/views/admin/borrows/index.html.erb
<% provide(:title, t(".manage_borrow")) %>
<nav aria-label="breadcrumb" class="col-md-12">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t("home"), admin_root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t(".borrows") %></li>
  </ol>
</nav>
<%= line_chart @data %>
<h4><%= t ".chart_borrow" %></h4>
<div class="row col-md-12">
  <%= link_to content_tag(:i, t(".filter"), class: "fa fa-filter"), "",
    class: "btn filter-show" %>
  <%= link_to content_tag(:i, t(".create_request"), class: "fa fa-hand-paper-o"),
    "", remote: true, data: {toggle: "modal", target: "#myModal"},
    class: "btn" %>
  <div class="col-md-12 filter hidden">
    <%= form_tag url_for, remote: true, method: :get do %>
      <div class="form-group">
        <div class="input-group">
          <div class="col-md-2">
            <%= label_tag :user_name, t(".user") %>
            <%= text_field_tag :user_name, params[:user_name], class: "form-control" %>
          </div>
          <div class="col-md-3">
            <%= label_tag :book_title, t(".book_title") %>
            <%= text_field_tag :book_title, params[:book_title], class: "form-control" %>
          </div>
          <div class="col-md-2">
            <%= label_tag :status, t(".status") %>
            <%= select_tag :status,
                options_for_select([:waitting, :active, :refuse, :cancelled, :returned, :lated]),
                prompt: "Status", class: "form-control" %>
          </div>
          <div class="col-md-2 px-1">
            <%= label_tag :from_date, t(".from_date") %>
            <%= date_field_tag :from_date, nil, class: "form-control" %>
          </div>
          <div class="col-md-2 px-1">
            <%= label_tag :to_date, t(".to_date") %>
            <%= date_field_tag :to_date, nil, class: "form-control" %>
          </div>
          <div class="">
            <br>
            <%= submit_tag "Search", name: nil, class: "btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="col-md-12 mt-3">
  <table class="table table-bordered table-hover bg-lightblue">
    <thead>
      <tr class="text-center">
        <th><%= t(".user_name") %></th>
        <th><%= t(".book_title") %></th>
        <th><%= t(".date_borrow") %></th>
        <th><%= t(".borrow_days") %></th>
        <th><%= t(".status") %></th>
        <th><%= t(".date_return") %></th>
      </tr>
    </thead>
    <tbody id="borrow-table" class="bg-white">
      <%= render "table" %>
    </tbody>
  </table>
  <div id="pagination">
    <%= paginate @borrows, remote: true, window: 2, theme: "twitter-bootstrap-4",
      pagination_class: "justify-content-center" %>
  </div>
</div>

app/views/admin/borrows/index.js.erb
$("#borrow-table").html("<%= escape_javascript render "table" %>")
$("#pagination").html("<%= escape_javascript(paginate @borrows, remote: true,
  window: 2, theme: "twitter-bootstrap-4",
  pagination_class: "justify-content-center") %>")

$("html, body").animate({ scrollTop: 0 }, "fast")

app/views/admin/borrows/update.js.erb
$("#borrow-<%= @borrow.id %>").html("<%=  escape_javascript(render @borrow)%>");